apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  # namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: waithaka.azurecr.io/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
          volumeMounts:
            - mountPath: /app/data
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: backend-pvc
